name: Reward Pull Request
on:
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  reward-contributor:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'bounty')
    steps:
      - uses: moodymatt/tx@marketplace
        with:
          rpc-node: "https://kovan.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          wallet-key: ${{ secrets.WALLET_KEY }}
          to:  ${{ secrets.RECIPIENT_ADDRESS }}
          value: "1"