name: Reward Pull Request
on:
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  reward-contributor:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'bounty')
    steps:
      - uses: web3actions/tx@marketplace
        with:
          rpc-node: "https://7c141ed2aa98.ngrok.io"
          wallet-key: ${{ secrets.WALLET_KEY }}
          to:  ${{ RECIPIENT_ADDRESS }}
          message: "heyo"
